version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.12.10-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    restart: always
    networks:
      - nest
  postgresql:
    container_name: pg-container
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    restart: always
    networks:
      - nest
  redis:
    container_name: redis-container
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./containers/data/redis/data:/data
      - ./containers/data/redis/conf/redis.conf:/usr/local/conf/redis.conf
    restart: always
    networks:
      - nest
networks:
  nest: