version: '3.8'
services:
  dev-db:
    container_name: pg-container
    image: postgres:latest
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234qwer!
      POSTGRES_DB: nest
    networks:
      - nest
networks:
  nest: