version: '3.8'
services:
  kafka:
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "9092:9092"
    volumes:
      - "./containers/data/kafka:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    restart: always
  postgresql:
    container_name: pg-container
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234qwer!
      POSTGRES_DB: nest
    networks:
      - nest
  redis:
    container_name: redis-container
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./containers/data/redis/data:/data
      - ./containers/data/redis/conf/redis.conf:/usr/local/conf/redis.conf
    restart: always
    networks:
      - nest
networks:
  nest: