version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234qwer!
      POSTGRES_DB: nest
    networks:
      - nest
networks:
  nest: