apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nestjs
  name: nestjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "3000"
    spec:
      containers:
      - image: sylvius/metrics-nestjs
        name: metrics-nestjs
        ports:
        - containerPort: 3000
